group 'com.mparticle.mparticle_flutter_sdk'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.9.22'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace "com.mparticle.mparticle_flutter_sdk"

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 16
        compileSdkVersion 35
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation 'com.mparticle:android-core:5.79.0'
    implementation 'com.mparticle:android-rokt-kit:5.79.0'

    // Required for Rokt event subscription
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.6.1"

    // Required for gathering Android Advertising ID
    implementation 'com.google.android.gms:play-services-ads-identifier:18.0.1'

    // Recommended to query the Google Play install referrer
    implementation 'com.android.installreferrer:installreferrer:2.2'

    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    testImplementation 'junit:junit:4.13.2'
}
